### ISSUE TITLE
Stubs for the following libultra functions for Harvest Moon 64

### ISSUE THREAD

**Issue by AngheloAlf** [N64Recomp/N64ModernRuntime#28]
Reported in  N64Recomp/N64Recomp#70

- [ ] `osPfsNumFiles`
- [ ] `osPfsRepairId`
- [ ] `osEPiRawStartDma` (stub)

**Comment by dpchamps** [comment]
The game is Harvest Moon 64

**Comment by Mr-Wiseguy** [comment]
Many of these should not be implemented in librecomp, see my comment [here](https://github.com/N64Recomp/N64Recomp/issues/70#issuecomment-2155796505). `osPfsRepairId` and potentially the pfs functions are the only ones that would make sense to include in librecomp.

**Comment by AngheloAlf** [comment]
After a bit of digging, seems like Harvest Moon 64 only needs the following 3 functions provided by modern runtime:
- `osPfsNumFiles`
- `osPfsRepairId`
- `osEPiRawStartDma` (this one just needs to be a stub)

I updated the issue to only list the above ones.
